### ISSUE TITLE
Greetings！

### ISSUE THREAD

**Issue by PhyX-Meow** [AtomAlpaca/AtomAlpaca#3]
膜拜一下初中就学了这么多OI的大佬qwq
头像很可爱！
我是悟理，数学(被迫)和计算机科学爱好者，ArchLinux in wsl2 in win11 使用者（为了玩游戏）。
最喜欢的编程语言是 Julia，会写C++和Mathematica。
欢迎来交朋友ww

**Comment by PhyX-Meow** [comment]
BTW，是rqy酱的同学~

**Comment by AtomAlpaca** [comment]
好耶，很高兴认识你！
（顺便膜拜大佬

**Comment by PhyX-Meow** [comment]
：）

**Comment by AtomAlpaca** [comment]
> 膜拜一下初中就学了这么多OI的大佬qwq
其实我相当菜qwq，做过的OI题目里有一半是入门级别的水题（

**Comment by PhyX-Meow** [comment]
github上聊天过于不便，不如加个qq/tg/微信/whatever好友（缩
